name: Check pull request source branch
on:
  pull_request_target:
    types:
    - opened
    - reopened
    - synchronize
    
jobs:
  check-branches:
    name: Check branches
    runs-on: ubuntu-latest
    steps:
    - name: Check branches
      env:
        HEAD_REF: ${{ github.head_ref }}
        BASE_REF: ${{ github.base_ref }}
      if: [ "$HEAD_REF" != "dev" ] && [ "$BASE_REF" == "main" ]
      run: |
        echo "Merge requests to main branch are only allowed from dev branch."
        gh run cancel ${{ github.run_id }}
        gh run watch ${{ github.run_id }}
        