name: Django CI

on:
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    name: Django build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v3
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        # x64 or x86
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools
        pip-compile ./requirements/development.txt --output-file ./full-requirements.txt --resolver=backtracking
        pip install -r ./full-requirements.txt

    - name: Lint with ruff
      run: |
        pip install ruff
        # stop the build if there are Python syntax errors or undefined names
        ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
      continue-on-error: true

    - name: Tests and coverage
      run: |
        export PYTHONPATH="$PYTHONPATH:./django-napse/"
        export IS_IN_PIPELINE=True
        coverage run ./test/test_app/manage.py test -v2 --keepdb && coverage html

    - name: Coverage value
      run: |
        cvg_result=$(coverage report --skip-covered | head -n -2 | tail -n 1 | awk '{print $NF}' | sed 's/%//')
        echo "COVERAGE=$cvg_result" >> $GITHUB_ENV

    - name: Coverage badge
      uses: Schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.NAPSE_SECRET_GIST }}
        gistID: 40fac957532fe3b731c99067467de842
        filename: django-napse-coverage.json
        label: Coverage
        message: ${{ env.COVERAGE }} %
        valColorRange: ${{ env.COVERAGE }}
        minColorRange: 50 
        maxColorRange: 95
