name: Django CI

on:
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    name: Django build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        # x64 or x86
        architecture: 'x64'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with ruff
      run: |
        pip install ruff
        # stop the build if there are Python syntax errors or undefined names
        ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
      continue-on-error: true

    - name: Run Tests
      run: |
        export PYTHONPATH="$PYTHONPATH:./django-napse/"
        python ./test/test_app/manage.py test --parallel