name: Django CI

on:
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    name: Django build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v3
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        # x64 or x86
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools
        pip-compile ./requirements/development.txt --output-file ./full-requirements.txt --resolver=backtracking
        pip install -r ./full-requirements.txt

    - name: Lint with ruff
      run: |
        pip install ruff
        # stop the build if there are Python syntax errors or undefined names
        ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
      continue-on-error: true

    - name: Tests and coverage
      run: |
        export PYTHONPATH="$PYTHONPATH:./django-napse/"
        export IS_IN_PIPELINE=True
        pip install coverage-badge
        coverage run ./test/test_app/manage.py test -v2 --keepdb && coverage html
        coverage-badge

    - name: Github reference
      run: echo "github reference - ${{ github.ref }}"
    
    - name: Checkout gh-pages
      run: git checkout gh-pages

    
