name: Release

on:
  push:
    branches: ["main", "dev", "feature/ci"]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - name: Install semantic-release
      run: |
        npm install --save-dev semantic-release
        npx semantic-release
    - name: Install semantic-release extra plugins
      run: npm install --save-dev @semantic-release/git      
    # - name: Lint
    #   run: npm run lint-fix
    # - name: Test
    #   run: npm run test:unit --if-present
    # - name: Build
    #   run: npm run build      
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx semantic-release