name: Release

on:
  push:
    branches: ["main", "feature/ci"]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Install semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm install --save-dev semantic-release
        npx semantic-release
    - name: Install semantic-release extra plugins
      run: npm install --save-dev @semantic-release/git @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/release-notes-generator       
    - name: Release
      run: npx semantic-release --ci